### ISSUE TITLE
the pipeline breaks often and the test sets is not working either

### ISSUE THREAD

**Issue by ILM-MLOlab** [nf-core/hicar#73]
### Description of the bug

I have trouble running the hicar pipeline, I first run within the screen and interactive session, using Conda as the environment, but then it breaks, after researching online knowing that it break easily so I switched to singularity and then also put a cap on the GPU(12) and memory(80G), but then it still breaks and when I resume it, sometimes it pick up the pipeline then later it might break at various steps. I asked the help from NBIS with the drop in session this week and then was looking at my parameter and help me to send it to SLURM, but it wouldn't work. Then the mentor asked me to run the test function and also failed. Therefore, I was advised to post the issue here and hopefully can receive some help from the developer. Thank you!

### Command used and terminal output

```console
$./nextflow run nf-core/hicar -r 1.0.0 -c parameter_PE_conda.config
I run the above command and gave me the error message below
Error executing process > 'NFCORE_HICAR:HICAR:INPUT_CHECK:SAMPLESHEET_CHECK (HiChIP_H3K27ac_design.csv)'

Caused by:
  Process `NFCORE_HICAR:HICAR:INPUT_CHECK:SAMPLESHEET_CHECK (HiChIP_H3K27ac_design.csv)` terminated with an error exit status (1)

Command executed:

  check_samplesheet.py \
      HiChIP_H3K27ac_design.csv \
      samplesheet.valid.csv
  
  cat <<-END_VERSIONS > versions.yml
  "NFCORE_HICAR:HICAR:INPUT_CHECK:SAMPLESHEET_CHECK":
      python: $(python --version | sed 's/Python //g')
  END_VERSIONS

Command exit status:
  1

Command output:
  (empty)

Command error:
  /sw/lmod/lmod/init/bash: line 16: __lmod_vx: unbound variable
    File "/home/gloriawu/.nextflow/assets/nf-core/hicar/bin/check_samplesheet.py", line 42
      **kwargs,
              ^
  SyntaxError: invalid syntax

Work dir:
  /home/gloriawu/snic2020-12-1/working/ENCODE/72/bf192b0cba5d0a0af80e2e3810f81d

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`


Failed to invoke `workflow.onComplete` event handler

 -- Check script '/home/gloriawu/.nextflow/assets/nf-core/hicar/./workflows/hicar.nf' at line: 498 or see '.nextflow.log' file for more details

Then I tried to have the below command just to test the pipeline, but it end with error also. Which I did not note down unfortunately.
$./nextflow run nf-core/hicar -r 1.0.0 -profile test,singularity -process.executor='slurm'
```

### System information

Nextflow version 22.04.5
Hardware Lunarc 
Executer both local and slurm
container singularity and Conda
version of nf-core/hicar 1.0.0

**Comment by jianhong** [comment]
Thank you for reporting this issue. The pipeline does not compatible with python version lower than 3.5. You can simply remove the trailing comma after `**kwargs` in check_samplesheet.py to let it run. However, it still will be failed at CUSTOM_DUMPSOFTWAREVERSIONS.
